// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// PLAT-8 (docs/specs/core-platform.md): migration commands use DIRECT_URL when
// it is set (an unpooled connection, which migrations need) and fall back to
// DATABASE_URL otherwise, so local work needs no second variable. This runs
// outside Next, so it reads `process.env` directly rather than through
// lib/env.ts (RULES.md: tooling configs are exempt).
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // TEST-11 (docs/specs/core-testing.md): `pnpm db:seed` → `prisma db seed`
    // → this. `tsx` is a dev dependency (owner-approved 2026-09-30, ADR 0014)
    // used only here, because Prisma 7's generated client uses extensionless
    // imports that Node's own type stripping cannot resolve.
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env.DIRECT_URL ?? process.env.DATABASE_URL,
    // Prisma 7 needs this to run `migrate dev` or `migrate diff` against a
    // migrations directory — it applies every migration here, throwaway,
    // rather than to the real database. Local-only: always the Compose
    // Postgres (pnpm db:up), never Neon, so production's DIRECT_URL/
    // DATABASE_URL never reach this branch.
    shadowDatabaseUrl: process.env.SHADOW_DATABASE_URL,
  },
});
